defmodule NextSteps.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :first_name, :text
      add :date_of_birth, :date
      add :email, :text
      add :gross_income, :float
      add :is_robot, :boolean
      add :last_name, :text
      add :last_login_at, :utc_datetime
      add :target_retirement_age, :float
      add :tax_filing_status_id, :uuid
    end

    create table(:tax_filing_status, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:users) do
      modify :tax_filing_status_id,
             references(:tax_filing_status,
               column: :id,
               name: "users_tax_filing_status_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:tax_filing_status) do
      add :status, :text
      add :description, :text
    end

    create table(:tax_deductions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :year, :bigint
      add :name, :text
      add :slug, :text
      add :amount, :decimal

      add :tax_filing_status_id,
          references(:tax_filing_status,
            column: :id,
            name: "tax_deductions_tax_filing_status_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:tax_brackets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :year, :bigint
      add :minimum_limit, :decimal
      add :maximum_limit, :decimal

      add :tax_filing_status_id,
          references(:tax_filing_status,
            column: :id,
            name: "tax_brackets_tax_filing_status_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:retirement_roth_iras, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :balance, :decimal
      add :monthly_contribution, :decimal
      add :yearly_total_contribution, :decimal
      add :effective_on, :utc_datetime
      add :expired_at, :utc_datetime

      add :user_id,
          references(:users,
            column: :id,
            name: "retirement_roth_iras_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:retirement_ira_limits, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :year, :bigint
      add :roth_type, :text
      add :agi_income_cap, :decimal
      add :limit_amount, :decimal
      add :over_50_catchup, :decimal
      add :description, :text

      add :tax_filing_status_id,
          references(:tax_filing_status,
            column: :id,
            name: "retirement_ira_limits_tax_filing_status_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:retirement_401ks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :balance, :decimal
      add :monthly_contribution, :decimal
      add :employer_match, :decimal
      add :employer_match_type, :text
      add :yearly_total_contribution, :decimal
      add :effective_on, :utc_datetime
      add :expired_at, :utc_datetime

      add :user_id,
          references(:users,
            column: :id,
            name: "retirement_401ks_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:retirement_401k_annual_limits, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :year, :bigint
      add :individual_limit, :decimal
      add :employer_limit, :decimal
      add :combined_limit, :decimal
      add :over_50_catchup, :decimal
      add :description, :text

      add :tax_filing_status_id,
          references(:tax_filing_status,
            column: :id,
            name: "retirement_401k_annual_limits_tax_filing_status_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:health_savings_accounts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :balance, :decimal
      add :yearly_contribution, :decimal
      add :monthly_contribution, :decimal
      add :employer_match, :decimal
      add :employer_match_type, :text
      add :effective_on, :utc_datetime
      add :expired_at, :utc_datetime

      add :user_id,
          references(:users,
            column: :id,
            name: "health_savings_accounts_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:emergency_savings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :balance, :decimal
      add :account_number, :text
      add :account_nickname, :text
      add :effective_on, :utc_datetime

      add :user_id,
          references(:users,
            column: :id,
            name: "emergency_savings_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:dependent_529s, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :balance, :decimal
      add :yearly_contribution, :decimal
      add :monthly_contribution, :decimal
      add :effective_on, :utc_datetime
      add :expired_at, :utc_datetime

      add :user_id,
          references(:users,
            column: :id,
            name: "dependent_529s_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:brokerage_accounts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :balance, :decimal
      add :account_number, :text
      add :effective_on, :utc_datetime

      add :user_id,
          references(:users,
            column: :id,
            name: "brokerage_accounts_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:brokerage_accounts, "brokerage_accounts_user_id_fkey")

    drop table(:brokerage_accounts)

    drop constraint(:dependent_529s, "dependent_529s_user_id_fkey")

    drop table(:dependent_529s)

    drop constraint(:emergency_savings, "emergency_savings_user_id_fkey")

    drop table(:emergency_savings)

    drop constraint(:health_savings_accounts, "health_savings_accounts_user_id_fkey")

    drop table(:health_savings_accounts)

    drop constraint(
           :retirement_401k_annual_limits,
           "retirement_401k_annual_limits_tax_filing_status_id_fkey"
         )

    drop table(:retirement_401k_annual_limits)

    drop constraint(:retirement_401ks, "retirement_401ks_user_id_fkey")

    drop table(:retirement_401ks)

    drop constraint(:retirement_ira_limits, "retirement_ira_limits_tax_filing_status_id_fkey")

    drop table(:retirement_ira_limits)

    drop constraint(:retirement_roth_iras, "retirement_roth_iras_user_id_fkey")

    drop table(:retirement_roth_iras)

    drop constraint(:tax_brackets, "tax_brackets_tax_filing_status_id_fkey")

    drop table(:tax_brackets)

    drop constraint(:tax_deductions, "tax_deductions_tax_filing_status_id_fkey")

    drop table(:tax_deductions)

    alter table(:tax_filing_status) do
      remove :description
      remove :status
    end

    drop constraint(:users, "users_tax_filing_status_id_fkey")

    alter table(:users) do
      modify :tax_filing_status_id, :uuid
    end

    drop table(:tax_filing_status)

    drop table(:users)
  end
end
